# This is a basic workflow to help you get started with Actions

name: testing_what's_installed

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  first_build_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: something like checkout is being done
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Find directories in this file
        run: ls -lah
        
      - name: Mkdir
        run: mkdir directory
        
      - name: Find directories in this file
        run: ls -lah
        
      - name: Teeing to create file
        run: echo "Creating a file" | tee anotheR_file
        
      - name: DF
        run: df -h
        
      - name: remove android
        run: sudo rm /usr/local/lib/android/sdk -rf
        
      - name: DF
        run: df -h
        
      - name: Remove Nodejs
        run: |
          sudo apt-get remove nodejs npm
          sudo apt-get purge nodejs
          sudo rm -rf /usr/local/bin/npm 
          sudo rm -rf /usr/local/share/man/man1/node* 
          sudo rm -rf /usr/local/lib/dtrace/node.d
          rm -rf ~/.npm
          rm -rf ~/.node-gyp
          sudo rm -rf /opt/local/bin/node
          sudo rm -rf /opt/local/include/node
          sudo rm -rf /opt/local/lib/node_modules
          sudo rm -rf /usr/local/lib/node*
          sudo rm -rf /usr/local/include/node*
          sudo rm -rf /usr/local/bin/node*
          
      - name: DF after
        run: df -h
        
      - name: will this run
        run: echo yes this is running | tee file is created
        
      - name: ls
        run: ls
      
      - name: uname
        run: uname -a
        
      - name: list of all things installed
        run: sudo apt --installed list

      - name: uninstall dotnet things
        run: sudo apt-get remove --purge dotnet-*3*
        
      - name: DF after
        run: df -h
